#!/usr/bin/env python3
"""Inline style.css into index.html.

The NSW Health web filter returns HTTP 403 with an HTML block page for
style.css while allowing the HTML document through, so on those terminals the
app rendered completely unstyled. A request that is never made cannot be
blocked, so the stylesheet ships inside index.html instead.

style.css remains the source of truth — edit it, then run this script.
`npm test` fails if the two ever drift.

Usage:
    python3 tools/build-css.py          # rewrite index.html in place
    python3 tools/build-css.py --check  # exit 1 if index.html is out of date
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
STYLESHEET = ROOT / "style.css"

BEGIN = "<!-- BEGIN style.css -->"
END = "<!-- END style.css -->"

# Matches the whole managed region including the markers, so rebuilds replace
# rather than accumulate.
REGION = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END),
    re.DOTALL,
)


def build_region(css: str) -> str:
    # Indented to sit naturally inside <head>. The CSS itself is emitted
    # verbatim so the checked-in copy can be compared byte for byte.
    return (
        f"{BEGIN}\n"
        "    <!-- Generated by tools/build-css.py. Do not edit here — edit style.css\n"
        "         and re-run the script. Inlined rather than linked because the NSW\n"
        "         Health web filter blocks the separate stylesheet request. -->\n"
        "    <style>\n"
        f"{css}\n"
        "    </style>\n"
        f"    {END}"
    )


def main() -> int:
    check_only = "--check" in sys.argv

    if not INDEX.exists() or not STYLESHEET.exists():
        print("error: index.html or style.css not found", file=sys.stderr)
        return 2

    html = INDEX.read_text(encoding="utf-8")
    css = STYLESHEET.read_text(encoding="utf-8").rstrip("\n")

    if "</style>" in css.lower():
        print("error: style.css contains '</style>' and cannot be inlined safely",
              file=sys.stderr)
        return 2

    if not REGION.search(html):
        print(f"error: markers {BEGIN} ... {END} not found in index.html",
              file=sys.stderr)
        return 2

    # re.sub would interpret backslashes and \g in the CSS as group references.
    updated = REGION.sub(lambda _: build_region(css), html, count=1)

    if updated == html:
        print("index.html is up to date")
        return 0

    if check_only:
        print("error: index.html is out of date — run: python3 tools/build-css.py",
              file=sys.stderr)
        return 1

    INDEX.write_text(updated, encoding="utf-8")
    print(f"inlined {len(css)} bytes of CSS into index.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
