#!/usr/bin/env python3
"""Mint site access codes and regenerate data/cohorts.js.

The app never contains the codes themselves, only a SHA-256 of each one. This
script is the only place the plaintext exists, and it prints it once for you to
distribute. Losing a code means minting a new one for that site — there is no
recovery, by design.

Input is a plain text file, one site per line:

    id | Site name | Setting

    dubbo-ed      | Dubbo Health Service   | Emergency Department
    dubbo-ward    | Dubbo Health Service   | Inpatient ward
    bathurst-ed   | Bathurst Health Service| Emergency Department

`id` is what gets recorded against every event. Keep it short, lowercase and
stable: renaming one after rollout splits that site's data in two.

    python3 tools/make-cohort-codes.py sites.txt
    python3 tools/make-cohort-codes.py sites.txt --write

Without --write it prints what it would do and changes nothing.
"""

import argparse
import hashlib
import re
import secrets
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
COHORTS_JS = REPO / "data" / "cohorts.js"

# No O/0, I/1, S/5, Z/2: these codes get read off a printed sheet taped to a
# wall and typed into a phone at 3am, and a confusable character there costs a
# support call.
ALPHABET = "ABCDEFGHJKLMNPQRTUVWXY346789"
SUFFIX_LEN = 4
ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]{0,39}$")


def normalise(code):
    """Fold a typed code to its canonical form.

    Case, spaces and hyphens are all forgiven, so `wnsw dubbo ed 7f2k` and
    `WNSW-DUBBO-ED-7F2K` are the same code. The hash is taken over this form,
    and the app applies exactly the same rule before hashing.
    """
    return re.sub(r"[^A-Z0-9]", "", code.upper())


def sha256_hex(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def mint(cohort_id):
    suffix = "".join(secrets.choice(ALPHABET) for _ in range(SUFFIX_LEN))
    return f"WNSW-{cohort_id.upper()}-{suffix}"


def parse_sites(path):
    sites = []
    seen = set()
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 3:
            sys.exit(f"{path}:{lineno}: expected 'id | Site name | Setting', got: {line}")
        cohort_id, site, setting = parts
        if not ID_PATTERN.match(cohort_id):
            sys.exit(f"{path}:{lineno}: id must be lowercase letters, digits and hyphens: {cohort_id}")
        if cohort_id in seen:
            sys.exit(f"{path}:{lineno}: duplicate id: {cohort_id}")
        seen.add(cohort_id)
        sites.append({"id": cohort_id, "site": site, "setting": setting})
    if not sites:
        sys.exit(f"{path}: no sites found.")
    return sites


def js_string(text):
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_js(entries):
    lines = [
        "// Site access codes — generated by tools/make-cohort-codes.py. Do not hand-edit.",
        "//",
        "// The codes themselves are NOT here. Each entry carries a SHA-256 of the",
        "// normalised code, so the bundle a clinician downloads cannot be read to",
        "// recover a working code. That is a real barrier but not a strong one: the",
        "// codes are short, so a determined person with the hash list could grind",
        "// through the suffix space. They are a cohort label and an intended-use",
        "// boundary, not a secret — see IMPLEMENTATION_NOTES.md.",
        "//",
        "// `id` is recorded against every event this site produces. Renaming one",
        "// after rollout splits that site's data in two; mint a new site instead.",
        "",
        "export const COHORTS = [",
    ]
    for entry in entries:
        lines.append("    {")
        lines.append(f"        id: {js_string(entry['id'])},")
        lines.append(f"        site: {js_string(entry['site'])},")
        lines.append(f"        setting: {js_string(entry['setting'])},")
        lines.append(f"        hash: '{entry['hash']}',")
        lines.append("    },")
    lines.extend([
        "];",
        "",
        "// Case, spaces and hyphens are forgiven: the code is read off a printed",
        "// sheet and typed on a phone. tools/make-cohort-codes.py applies exactly",
        "// this rule before hashing, and a test asserts the two agree.",
        "export function normaliseCode(code) {",
        "    return String(code).toUpperCase().replace(/[^A-Z0-9]/g, '');",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("sites", type=Path, help="text file of 'id | Site name | Setting' lines")
    parser.add_argument("--write", action="store_true", help="write data/cohorts.js (otherwise dry run)")
    args = parser.parse_args()

    if not args.sites.exists():
        sys.exit(f"No such file: {args.sites}")

    sites = parse_sites(args.sites)
    for entry in sites:
        code = mint(entry["id"])
        entry["code"] = code
        entry["hash"] = sha256_hex(normalise(code))

    width = max(len(e["code"]) for e in sites)
    print("\nCodes to distribute — printed once, recorded nowhere else:\n")
    print(f"  {'CODE'.ljust(width)}  SITE")
    print(f"  {'-' * width}  {'-' * 40}")
    for entry in sites:
        print(f"  {entry['code'].ljust(width)}  {entry['site']} — {entry['setting']}")

    print("\nCohort ids for the worker (set COHORTS to this):\n")
    print("  " + ",".join(e["id"] for e in sites))

    js = render_js(sites)
    if args.write:
        COHORTS_JS.write_text(js, encoding="utf-8")
        print(f"\nWrote {COHORTS_JS.relative_to(REPO)} ({len(sites)} sites).")
        print("Commit that file. Do NOT commit the codes above.\n")
    else:
        print(f"\nDry run — {COHORTS_JS.relative_to(REPO)} not written. Re-run with --write.\n")


if __name__ == "__main__":
    main()
